apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: eureka-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: eureka-server
          image: eureka-service:latest  # Docker image ad覺n覺z覺 burada yaz覺n
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_APPLICATION_NAME
              value: eureka-server
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "true"
            - name: EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS
              value: "60000"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SERVER_PORT
              value: "8761"
