apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  labels:
    app: eureka-server
spec:
  type: NodePort  # Servisi Minikube üzərindən əlçatan etmək üçün
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30001  # Minikube'də port təyin edirik
  selector:
    app: eureka-server
